### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Mekcyed** [LevantinLynx/gotify-to-ntfy-proxy#3]
Hi and thank you for this project!

I am running ntfy and gotify-to-ntfy-proxy in the same LXC Container on my proxmox host.

gotify-to-ntfy-proxy config:

```yaml
version: '3.9'
services:
  gotify-to-ntfy-proxy:
    image: 'levantinlynx/gotify-to-ntfy-proxy:latest'
    restart: unless-stopped
    container_name: gotify-to-ntfy-proxy
    volumes:
      - '/home/vmadmin/gotify-to-ntfy-proxy/topics.js:/home/node/app/topics.js'
    ports:
      - '8008:8008'
    environment:
      - RELAY_HOST_IP=0.0.0.0
      - RELAY_PORT=8008
      - NTFY_SERVER=https:/192.168.178.209

```

```js
const topics = {
  proxmox: {
    ntfyToken: 'tested_valid_token'
  }
}

module.exports = topics
```

ntfy config:

```yaml
version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      TZ: Europe/Berlin    # optional: set desired timezone
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ENABLE_LOGIN: false
    user: 1000:1000 # optional: replace with your own user/group or uid/gid
    volumes:
      - /home/vmadmin/ntfy:/var/lib/ntfy
    ports:
      - 80:80
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
```
Proxmox:
![grafik](https://github.com/user-attachments/assets/4794bdc9-20db-40ab-9c6d-cc83d7f87bc8)

When sending a test notification via proxmox ui i get this Error:

![grafik](https://github.com/user-attachments/assets/edcad413-14e5-4eb5-ab76-8beb2497b3ad)

```
2024-08-30T07:15:46.738Z           storyboard INFO  ┌─── ROOT STORY: Node.js 22.4.1 on Linux 64-bit, SB 3.3.2 [ ·CREATED]
2024-08-30T07:15:46.739Z           storyboard INFO  Log filter: *:DEBUG
2024-08-30T07:15:46.780Z           storyboard INFO  Log filter is now: *:INFO
2024-08-30T07:25:29.466Z                 NTFY ERROR connect ECONNREFUSED 192.168.178.209:443
2024-08-30T07:15:46.786Z               SERVER INFO  Relay Server is listening on http://0.0.0.0:8008
2024-08-30T07:15:46.780Z          ENVIRONMENT INFO  Running in PRODUCTION mode!
                                         NTFY ERROR   stack:     at eventHandlers.<computed> (/home/node/app/node_modules/follow-redirects/index.js:38:24)
                                         NTFY ERROR   stack:     at RedirectableRequest.emit (node:events:520:28)
                                         NTFY ERROR   stack:     at RedirectableRequest.handleRequestError (/home/node/app/node_modules/axios/dist/node/axios.cjs:3106:25)
                                         NTFY ERROR   stack: Error: connect ECONNREFUSED 192.168.178.209:443
                                         NTFY ERROR   name: 'Error'
                                         NTFY ERROR   message: 'connect ECONNREFUSED 192.168.178.209:443'
                                         NTFY ERROR   stack:     at AxiosError.from (/home/node/app/node_modules/axios/dist/node/axios.cjs:841:14)
                                         NTFY ERROR   stack:     at ClientRequest.emit (node:events:520:28)
                                         NTFY ERROR   stack:     at TLSSocket.socketErrorListener (node:_http_client:502:9)
                                         NTFY ERROR   stack:     at TLSSocket.emit (node:events:520:28)
                                         NTFY ERROR   stack:     at emitErrorNT (node:internal/streams/destroy:170:8)
                                         NTFY ERROR   stack:     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
                                         NTFY ERROR   stack:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
                                         NTFY ERROR   stack:     at Axios.request (/home/node/app/node_modules/axios/dist/node/axios.cjs:4224:41)
                                         NTFY ERROR   stack:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                         NTFY ERROR   stack:     at async sendNotificationToNtfyServer (/home/node/app/ntfy.js:33:20)
                                         NTFY ERROR   stack:     at async /home/node/app/index.js:81:15
2024-08-30T07:25:29.468Z           storyboard INFO  └─── ROOT STORY: Node.js 22.4.1 on Linux 64-bit, SB 3.3.2 [ ·CLOSED]
/home/node/app/index.js:84
    id: msg.id,
            ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /home/node/app/index.js:84:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v22.4.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Do you have a clue what my problem is here?

**Comment by LevantinLynx** [comment]
Well it says it right there in the Error message, the ntfy server refuses the connection on port 443. As far as i can see in your config you host it on port 80 so http and not https as defined in your docker compose.

**Comment by Mekcyed** [comment]
And additionally the second slash was missing... Stupid... Sorry for disturbing you :(
